base.py: Use none interpolation for ConfigParser
When character '%' is used in auth_password, the ConfigParser will raise
InterpolationSyntaxError because the ConfigParser in default interpolation[1]
parses '%' as formatting character

It will report the error like:
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%'

[1]: https://docs.python.org/3.6/library/configparser.html#interpolation-of-values

Signed-off-by: Han Han <hhan@redhat.com>